> **Задание 1**
>
> Поместите текстовое поле на экран
> import tkinter as tk
> root = tk.Tk()
> root.geometry("800x500")
> root.title("задание 1")
> textbox = tk.Text(root, height=3, font=("Arial", 16))
> textbox.pack(padx=20, pady=20)
> root.mainloop()
> (помогтеееееееепеее😭😭😭😭😭😰😰😰😰😰😰😰😨😨😨😩😩😩😩😩🤯🤯🤯😬😬😬)

> **Задание 2**
>
> Приведите калькулятор к следующему виду
root.title("КУЛЬКУЛЯТОР")
> label = tk.Label(root, text="раз два три четыре пять зайчик вышел погулять", font=("Arial", 18))
> label.pack(padx=20, pady=20,)
> textbox = tk.Text(root, height=3, font=("Arial", 16), bg="#E0FFFF")
> textbox.pack()
> buttonFrame = tk.Frame(root)
> buttonFrame.columnconfigure(0, weight=1)
> buttonFrame.columnconfigure(1, weight=1)
> buttonFrame.columnconfigure(2, weight=1)
> buttonFrame.columnconfigure(3, weight=1)
> btn1 = tk.Button(buttonFrame, text="1", font=("Arial", 18), bg="#8B0000")
> btn1.grid(row=1, column=0, sticky="we")
> btn2 = tk.Button(buttonFrame, text="2", font=("Arial", 18), bg="#E9967A")
> btn2.grid(row=1, column=1, sticky="we")
> btn3 = tk.Button(buttonFrame, text="3", font=("Arial", 18), bg="#FFD700")
> btn3.grid(row=1, column=2, sticky="we")
> btn4 = tk.Button(buttonFrame, text="-", font=("Arial", 18), bg="#008080")
> btn4.grid(row=1, column=3, sticky="we")
> btn5 = tk.Button(buttonFrame, text="4", font=("Arial", 18), bg="#556B2F")
> btn5.grid(row=2, column=0, sticky="we")
> btn6 = tk.Button(buttonFrame, text="5", font=("Arial", 18), bg="#6495ED")
> btn6.grid(row=2, column=1, sticky="we")
> btn7 = tk.Button(buttonFrame, text="6", font=("Arial", 18), bg="#191970")
> btn7.grid(row=2, column=2, sticky="we")
> btn9 = tk.Button(buttonFrame, text="+", font=("Arial", 18), bg="#008080")
> btn9.grid(row=2, column=3, sticky="we")
> btn10 = tk.Button(buttonFrame, text="7", font=("Arial", 18), bg="#9370DB")
> btn10.grid(row=3, column=0, sticky="we")
> btn11 = tk.Button(buttonFrame, text="8", font=("Arial", 18), bg="#FF69B4")
> btn11.grid(row=3, column=1, sticky="we")
> btn12 = tk.Button(buttonFrame, text="9", font=("Arial", 18), bg="#2F4F4F")
> btn12.grid(row=3, column=2, sticky="we")
> btn13 = tk.Button(buttonFrame, text="*", font=("Arial", 18), bg="#008080")
> btn13.grid(row=3, column=3, sticky="we")
> btn14 = tk.Button(buttonFrame, text="Clear", font=("Arial", 18), bg="#008080")
> btn14.grid(row=4, column=0, sticky="we")
> btn15 = tk.Button(buttonFrame, text="0", font=("Arial", 18), bg="#708090")
> btn15.grid(row=4, column=1, sticky="we")
> btn16 = tk.Button(buttonFrame, text="=", font=("Arial", 18), bg="#008080")
> btn16.grid(row=4, column=2, sticky="we")
> btn17 = tk.Button(buttonFrame, text="/", font=("Arial", 18), bg="#008080")
> btn17.grid(row=4, column=3, sticky="we")
> buttonFrame.pack(fill="x")
> root.mainloop()

![Пример](./.repo/images/example-1.png)
